version: "3.5"
services:
  edaport-develop-redis:
    image: redis:alpine
    container_name: edaport-develop-redis
    volumes:
      - edaport-develop-redis:/data
    ports:
      - "6379"
    restart: always
    networks:
      - edaport-develop

  edaport-develop-mysql:
    image: mysql:5.7.22
    container_name: edaport-develop-mysql
    working_dir: /application
    volumes:
      - stage_edaport-stage-mysql-data:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: KBHJ8765ljk767kh
      MYSQL_DATABASE: app
    restart: always
    ports:
      - "3306:3306"
    networks:
      - edaport-develop

  edaport-develop-webserver:
    image: nginx:latest
    container_name: edaport-develop-webserver
    working_dir: /application
    volumes:
      - /var/www/edaport/backend:/application
      - /var/www/frontend:/frontend
      - /var/www/manager:/manager
      - /var/www/edaport/storage:/var/www/edaport/storage
      - ./hosts:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/log/nginx/:/var/log/nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - edaport-develop
    links:
      - edaport-develop-php-fpm
      - edaport-develop-websocket

  edaport-develop-php-fpm:
    build: php-fpm
    container_name: edaport-develop-php-fpm
    working_dir: /application
    restart: always
    volumes:
      - /var/www/edaport/backend:/application
      - /var/www/edaport/storage:/var/www/edaport/storage
      - /var/www/edaport/composer:/var/www/edaport/composer
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      - /var/log/laravel/:/application/storage/logs/
    ports:
      - "9000"
    networks:
      - edaport-develop
    environment:
      APP_ENV: production
      CONTAINER_ROLE: app
    links:
      - edaport-develop-redis

  edaport-develop-scheduler:
    build: php-fpm
    container_name: edaport-develop-scheduler
    user: ${CURRENT_UID}
    restart: always
    volumes:
      - /var/www/edaport/backend:/application
      - /var/www/edaport/composer:/var/www/edaport/composer
    environment:
      APP_ENV: production
      CONTAINER_ROLE: scheduler
    networks:
      - edaport-develop
    links:
      - edaport-develop-redis

  edaport-develop-queue:
    build: php-fpm
    container_name: edaport-develop-queue
    user: ${CURRENT_UID}
    restart: always
    volumes:
      - /var/www/edaport/backend:/application
      - /var/www/edaport/composer:/var/www/edaport/composer
    environment:
      APP_ENV: production
      CONTAINER_ROLE: queue
    networks:
      - edaport-develop
    links:
      - edaport-develop-redis

  edaport-develop-websocket:
    build: php-fpm
    container_name: edaport-develop-websocket
    user: ${CURRENT_UID}
    restart: always
    volumes:
      - /var/www/edaport/backend:/application
      - /var/www/edaport/composer:/var/www/edaport/composer
    ports:
      - "6001"
    environment:
      APP_ENV: production
      CONTAINER_ROLE: websocket
    networks:
      - edaport-develop
    links:
      - edaport-develop-redis
    depends_on:
      - edaport-develop-redis

networks:
  edaport-develop:
    driver: bridge

volumes:
  stage_edaport-stage-mysql-data:
    external: true
  edaport-develop-redis:
    driver: "local"

